#!/bin/bash

BASEDIR=${OCP_BASE}
if [[ "$BASEDIR" == "" ]] && echo "Please define and export environment variable OCP_BASE with the full path to the location for the cluster's persistent data" && exit 1

if ! [ "$1" = "" ] ; then VERSION=$1 ; else VERSION=latest; fi

OCP_IMAGE=registry.access.redhat.com/openshift3/ose
IMAGES=("$OCP_IMAGE" "registry.access.redhat.com/openshift3/ose-docker-registry" "registry.access.redhat.com/openshift3/ose-haproxy-router" "registry.access.redhat.com/openshift3/ose-pod" "registry.access.redhat.com/openshift3/ose-deployer" "registry.access.redhat.com/openshift3/ose-sti-builder" "registry.access.redhat.com/openshift3/ose-docker-builder")

if [[ "$@" = *"--repull"* ]] ; then

  for image in "${IMAGES[@]}"
  do
     sudo docker pull ${image}:${VERSION}
  done

fi


[ -e ${BASEDIR}/config-${VERSION}/master/ca.crt ] && CA_EXISTS=1

sudo oc cluster up --use-existing-config \
              --host-config-dir="${BASEDIR}/config-${VERSION}" \
              --host-data-dir="${BASEDIR}/data-${VERSION}" \
              --host-volumes-dir="${BASEDIR}/volumes-${VERSION}" \
	      --image="${OCP_IMAGE}" \
	      --version=${VERSION} \
	      --metrics=true \
	      --logging=true \
	      --public-hostname='openshift.demo'

if [ ${CA_EXISTS} -ne 1 ]; then
	echo "** Adding CA-Trust **"
	sudo bash -c "cp ${BASEDIR}/config-${VERSION}/master/ca.crt /etc/pki/ca-trust/source/anchors/ ; update-ca-trust"
fi

sudo oc login -u system:admin
sudo oc adm policy add-cluster-role-to-user cluster-admin admin

oc login --username=admin --password=admin https://openshift.demo:8443

pushd pv
./create-pvs ${BASEDIR} ${VERSION}
popd

pushd templates
./prep-templates
popd

pushd alm
./init-alm
popd

pushd code
./create-demo-resources
./create-demo-projects
popd
