kind: Template
apiVersion: v1
metadata:
  name: monster-app
  annotations:
    tags: instant-app,javaee
    iconClass: icon-jboss
    description: |
      Deploy and run the Ticket Monster App, built in another project. Note: you must have permission to pull images from that project. 

parameters:
- name: IMAGE_TAG
  value: uat
  description: 'Please provide the image tag to watch for new deployments'
- name: DEV_NAMESPACE
  required: true
  description: 'Please provide the source project name'
- name: MYSQL_DATABASE
  value: monster
- name: MYSQL_USER
  value: monster
- name: MYSQL_PASSWORD
  from: '[a-zA-Z0-9]{8}'
  generate: expression

objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: monster
  spec:
    replicas: 1
    selector:
      deploymentConfig: monster
    template:
      metadata:
        labels:
          deploymentConfig: monster
        name: monster
      spec:
        containers:
        - name: monster
          image: monster
          ports:
          - name: http
            containerPort: 8080
          - name: jolokia
            containerPort: 8778
          - name: debug
            containerPort: 8787
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/readinessProbe.sh
          env:
          - name: DB_SERVICE_PREFIX_MAPPING
            value: monster-mysql=DB
          - name: TX_DATABASE_PREFIX_MAPPING
            value: monster-mysql=DB
          - name: DB_JNDI
            value: java:jboss/datasources/MySQLDS
          - name: DB_DATABASE
            value: ${MYSQL_DATABASE}
          - name: DB_USERNAME
            value: ${MYSQL_USER}
          - name: DB_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: JAVA_OPTS
            value: "-Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.logmanager -Djava.awt.headless=true -Djboss.modules.policy-permissions=true"
          - name: DEBUG
            value: "true"
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - monster
        from:
          kind: ImageStream
          name: monster:${IMAGE_TAG}
          namespace: ${DEV_NAMESPACE}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: monster-mysql
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - monster-mysql
        from:
          kind: ImageStreamTag
          name: mysql:latest
          namespace: openshift
    replicas: 1
    selector:
      deploymentConfig: monster-mysql
    template:
      metadata:
        labels:
          deploymentConfig: monster-mysql
        name: monster-mysql
      spec:
        containers:
        - name: monster-mysql
          image: mysql
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command: [/bin/sh, '-i', '-c', 'MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e ''SELECT 1''']
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
- kind: Service
  apiVersion: v1
  metadata:
    name: monster
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      deploymentConfig: monster

- kind: Service
  apiVersion: v1
  metadata:
    name: monster-mysql
  spec:
    ports:
    - port: 3306
    selector:
      deploymentConfig: monster-mysql

- kind: Route
  apiVersion: v1
  metadata:
    name: monster
  spec:
    to:
      name: monster
