#!/bin/bash

oc new-project alm

MYNIC=$(ip r | grep default | awk '{print $5'})
MYIP=$(ip addr show $MYNIC | grep -Po 'inet \K[\d.]+')

oc new-app -f gogs/openshift/gogs-persistent-template.yaml -p SKIP_TLS_VERIFY=true -p HOSTNAME=gogs-alm.${MYIP}.xip.io
oc new-app -f nexus/nexus3-persistent-template.yaml 

# confirm hostnames by explicitly requesting them
nexus_host=$(oc get route nexus -o jsonpath='{.spec.host}')
gogs_host=$(oc get route gogs -o jsonpath='{.spec.host}') 

printf "Waiting for Nexus"
until $(curl --output /dev/null --silent --fail http://$nexus_host/); do
   printf '.'
   sleep 5
done
echo "[OK]"
printf "Waiting for Gogs"
until $(curl --output /dev/null --silent --fail http://$gogs_host/); do
	printf '.'
	sleep 5
done
echo "[OK]"

