#!/bin/bash

VERSION=$(oc version | grep openshift.*v | awk '{print $2}')
IMAGE_VERSION=$(echo ${VERSION:0:4})

DOWNLOADURL=https://raw.githubusercontent.com/openshift/origin-metrics/enterprise/metrics.yaml
METRICSURL=$(sudo oc cluster status | grep '^Metrics' | grep -E -o 'https?://[^ ]+')
METRICSHOST=$(echo ${METRICSURL} | awk -F/ '{print $3}')

oc project openshift-infra

echo "*** Removing existing Metrics configuration"
oc delete all,sa,templates,secrets,pvc --selector="metrics-infra" 
oc delete sa,secret metrics-deployer 

TMPD=$(mktemp -d)

pushd ${TMPD}

oc create serviceaccount metrics-deployer
oc adm policy add-role-to-user edit system:serviceaccount:openshift-infra:metrics-deployer
oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:openshift-infra:heapster
oc secrets new metrics-deployer nothing=/dev/null

wget ${DOWNLOADURL} -O metrics-deployer.yaml

oc new-app --as=system:serviceaccount:openshift-infra:metrics-deployer \
    -f metrics-deployer.yaml \
    -p IMAGE_VERSION=${IMAGE_VERSION} \
    -p HAWKULAR_METRICS_HOSTNAME=${METRICSHOST}

popd

rm -rf ${TMPD}
